//! ECS-first scene stack primitives for Foundation games.
//!
//! The scene stack is data-driven: games and systems request stack mutations by
//! writing [`SceneCommand`] messages, while Foundation systems own the stack
//! resource and lifecycle messages. Jackdaw `.jsn` levels are represented as a
//! scene source instead of being converted into a separate Foundation-specific
//! scene format.

use bevy::prelude::*;

/// Installs FoundationLibrary scene stack resources and message types.
#[derive(Default)]
pub struct FoundationSceneStackPlugin;

impl Plugin for FoundationSceneStackPlugin {
    fn build(&self, app: &mut App) {
        app.init_resource::<SceneStack>()
            .add_message::<SceneCommand>()
            .add_message::<SceneAdded>()
            .add_message::<SceneRemoved>()
            .add_message::<SceneFocused>()
            .add_message::<SceneUnfocused>()
            .register_type::<SceneOwner>();
    }
}

/// Stable runtime identifier for a scene stack entry.
///
/// IDs are generated by the scene stack when an open command is applied. Use
/// [`SceneKey`] when game code needs a stable human-authored target.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, Reflect)]
pub struct SceneId(pub u64);

/// Optional human-authored scene key for targeting and diagnostics.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Reflect)]
pub struct SceneKey(pub String);

impl SceneKey {
    /// Creates a scene key from any string-like value.
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }
}

impl From<&str> for SceneKey {
    fn from(value: &str) -> Self {
        Self::new(value)
    }
}

impl From<String> for SceneKey {
    fn from(value: String) -> Self {
        Self::new(value)
    }
}

/// Describes where scene content comes from.
///
/// `.jsn` level files are first-class sources so FoundationLibrary can cooperate
/// with Jackdaw-authored levels without defining a second level format.
#[derive(Clone, Debug, PartialEq, Eq, Reflect)]
pub enum SceneSource {
    /// A Jackdaw `.jsn` level or scene file.
    JsnLevel { path: String },
    /// A runtime scene identified by key, such as a menu or overlay assembled by systems.
    Runtime { key: SceneKey },
}

impl SceneSource {
    /// Creates a source for a Jackdaw `.jsn` level file.
    pub fn jsn_level(path: impl Into<String>) -> Self {
        Self::JsnLevel { path: path.into() }
    }

    /// Creates a source for a runtime/system-authored scene.
    pub fn runtime(key: impl Into<SceneKey>) -> Self {
        Self::Runtime { key: key.into() }
    }
}

/// Describes how a scene affects scenes below it in the stack.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Reflect)]
pub struct ScenePresentation {
    /// If true, scenes below this one should not be visible.
    pub covers_previous: bool,
    /// If true, scenes below this one should not receive input.
    pub blocks_previous_input: bool,
    /// If true, scenes below this one should not update/simulate.
    pub blocks_previous_update: bool,
}

impl ScenePresentation {
    /// Full-screen/modal scene: hides, blocks input, and blocks updates below.
    pub const FULLSCREEN: Self = Self {
        covers_previous: true,
        blocks_previous_input: true,
        blocks_previous_update: true,
    };

    /// Pause-style overlay: keeps lower scenes visible but blocks input and updates.
    pub const PAUSE_OVERLAY: Self = Self {
        covers_previous: false,
        blocks_previous_input: true,
        blocks_previous_update: true,
    };

    /// UI overlay: keeps lower scenes visible/updating but blocks their input.
    pub const INPUT_BLOCKING_OVERLAY: Self = Self {
        covers_previous: false,
        blocks_previous_input: true,
        blocks_previous_update: false,
    };

    /// Debug-style overlay: leaves lower scenes visible, interactive, and updating.
    pub const NON_BLOCKING_OVERLAY: Self = Self {
        covers_previous: false,
        blocks_previous_input: false,
        blocks_previous_update: false,
    };
}

impl Default for ScenePresentation {
    fn default() -> Self {
        Self::FULLSCREEN
    }
}

/// Derived runtime flags for a scene stack entry.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Reflect)]
pub struct SceneRuntimeFlags {
    /// True when this scene owns primary focus.
    pub focused: bool,
    /// True when this scene should be visible.
    pub visible: bool,
    /// True when this scene may receive input.
    pub interactive: bool,
    /// True when this scene should update/simulate.
    pub updating: bool,
}

/// A single entry in the scene stack.
#[derive(Clone, Debug, PartialEq, Eq, Reflect)]
pub struct SceneStackEntry {
    /// Generated runtime id for this stack entry.
    pub id: SceneId,
    /// Optional stable target key for game-friendly lookup.
    pub key: Option<SceneKey>,
    /// Data source for the scene.
    pub source: SceneSource,
    /// Policy describing how this scene affects lower stack entries.
    pub presentation: ScenePresentation,
    /// Derived focus/visibility/input/update flags.
    pub flags: SceneRuntimeFlags,
}

/// Authoritative scene stack resource.
#[derive(Debug, Resource, Reflect)]
#[reflect(Resource)]
pub struct SceneStack {
    entries: Vec<SceneStackEntry>,
    next_id: u64,
}

impl Default for SceneStack {
    fn default() -> Self {
        Self {
            entries: Vec::new(),
            next_id: 1,
        }
    }
}

impl SceneStack {
    /// Returns all stack entries from bottom to top.
    pub fn entries(&self) -> &[SceneStackEntry] {
        &self.entries
    }

    /// Returns the top stack entry, if any.
    pub fn current(&self) -> Option<&SceneStackEntry> {
        self.entries.last()
    }

    /// Returns true when no scenes are stacked.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Returns the number of stacked scenes.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Returns the next id that will be assigned by command processing.
    pub fn next_scene_id(&self) -> SceneId {
        SceneId(self.next_id)
    }
}

/// Options used when opening a scene.
#[derive(Clone, Debug, Default, PartialEq, Eq, Reflect)]
pub struct OpenSceneOptions {
    /// Optional stable key for closing or finding the scene later.
    pub key: Option<SceneKey>,
    /// Presentation policy for the new scene.
    pub presentation: ScenePresentation,
    /// Remove all existing scenes before opening this scene.
    pub clear_stack: bool,
    /// Remove the current top scene before opening this scene.
    pub close_current: bool,
}

impl OpenSceneOptions {
    /// Sets the scene key.
    pub fn with_key(mut self, key: impl Into<SceneKey>) -> Self {
        self.key = Some(key.into());
        self
    }

    /// Sets the scene presentation policy.
    pub fn with_presentation(mut self, presentation: ScenePresentation) -> Self {
        self.presentation = presentation;
        self
    }

    /// Configures the open command to clear all existing scenes first.
    pub fn clear_stack(mut self) -> Self {
        self.clear_stack = true;
        self
    }

    /// Configures the open command to close the current top scene first.
    pub fn close_current(mut self) -> Self {
        self.close_current = true;
        self
    }
}

/// Target used by close commands.
#[derive(Clone, Debug, PartialEq, Eq, Reflect)]
pub enum SceneTarget {
    /// Close the scene with this generated id.
    Id(SceneId),
    /// Close the first scene with this game-authored key.
    Key(SceneKey),
}

impl From<SceneId> for SceneTarget {
    fn from(value: SceneId) -> Self {
        Self::Id(value)
    }
}

impl From<SceneKey> for SceneTarget {
    fn from(value: SceneKey) -> Self {
        Self::Key(value)
    }
}

/// Buffered request to mutate the scene stack.
#[derive(Clone, Debug, Message, PartialEq, Eq, Reflect)]
pub enum SceneCommand {
    /// Open a scene, optionally clearing or replacing existing entries first.
    Open {
        /// Scene source to open.
        source: SceneSource,
        /// Open behavior and presentation options.
        options: OpenSceneOptions,
    },
    /// Close the current top scene.
    CloseCurrent,
    /// Close a specific scene by id or key.
    Close(SceneTarget),
    /// Remove all scenes from the stack.
    Clear,
    /// Remove all scenes, then open the supplied scene.
    ClearAndOpen {
        /// Scene source to open after clearing.
        source: SceneSource,
        /// Open behavior and presentation options.
        options: OpenSceneOptions,
    },
}

impl SceneCommand {
    /// Creates an open command with default options.
    pub fn open(source: SceneSource) -> Self {
        Self::Open {
            source,
            options: OpenSceneOptions::default(),
        }
    }

    /// Creates an open command with explicit options.
    pub fn open_with_options(source: SceneSource, options: OpenSceneOptions) -> Self {
        Self::Open { source, options }
    }

    /// Creates a clear-and-open command with default open options.
    pub fn clear_and_open(source: SceneSource) -> Self {
        Self::ClearAndOpen {
            source,
            options: OpenSceneOptions::default(),
        }
    }
}

/// Message emitted after a scene is added to the stack.
#[derive(Clone, Debug, Message, PartialEq, Eq, Reflect)]
pub struct SceneAdded {
    /// Added scene id.
    pub scene_id: SceneId,
}

/// Message emitted after a scene is removed from the stack.
#[derive(Clone, Debug, Message, PartialEq, Eq, Reflect)]
pub struct SceneRemoved {
    /// Removed scene id.
    pub scene_id: SceneId,
}

/// Message emitted after a scene becomes focused.
#[derive(Clone, Debug, Message, PartialEq, Eq, Reflect)]
pub struct SceneFocused {
    /// Focused scene id.
    pub scene_id: SceneId,
}

/// Message emitted after a scene loses focus.
#[derive(Clone, Debug, Message, PartialEq, Eq, Reflect)]
pub struct SceneUnfocused {
    /// Unfocused scene id.
    pub scene_id: SceneId,
}

/// Tags entities that are owned by a scene stack entry.
///
/// Scene-owned entities should remain alive while their owning scene is in the
/// stack and be cleaned up when that scene is removed.
#[derive(Clone, Copy, Debug, Component, PartialEq, Eq, Reflect)]
#[reflect(Component)]
pub struct SceneOwner {
    /// Scene that owns this entity.
    pub scene_id: SceneId,
}

/// Convenience methods for queuing scene commands through Bevy [`Commands`].
pub trait SceneCommandsExt {
    /// Queues a command to open a scene with default options.
    fn open_scene(&mut self, source: SceneSource) -> &mut Self;

    /// Queues a command to open a scene with explicit options.
    fn open_scene_with_options(
        &mut self,
        source: SceneSource,
        options: OpenSceneOptions,
    ) -> &mut Self;

    /// Queues a command to close the current scene.
    fn close_current_scene(&mut self) -> &mut Self;

    /// Queues a command to close a target scene by id or key.
    fn close_scene(&mut self, target: impl Into<SceneTarget>) -> &mut Self;

    /// Queues a command to clear all scenes.
    fn clear_scenes(&mut self) -> &mut Self;

    /// Queues a command to clear all scenes and then open a new scene.
    fn clear_and_open_scene(&mut self, source: SceneSource) -> &mut Self;
}

impl<'w, 's> SceneCommandsExt for Commands<'w, 's> {
    fn open_scene(&mut self, source: SceneSource) -> &mut Self {
        self.queue_scene_command(SceneCommand::open(source))
    }

    fn open_scene_with_options(
        &mut self,
        source: SceneSource,
        options: OpenSceneOptions,
    ) -> &mut Self {
        self.queue_scene_command(SceneCommand::open_with_options(source, options))
    }

    fn close_current_scene(&mut self) -> &mut Self {
        self.queue_scene_command(SceneCommand::CloseCurrent)
    }

    fn close_scene(&mut self, target: impl Into<SceneTarget>) -> &mut Self {
        self.queue_scene_command(SceneCommand::Close(target.into()))
    }

    fn clear_scenes(&mut self) -> &mut Self {
        self.queue_scene_command(SceneCommand::Clear)
    }

    fn clear_and_open_scene(&mut self, source: SceneSource) -> &mut Self {
        self.queue_scene_command(SceneCommand::clear_and_open(source))
    }
}

trait QueueSceneCommand {
    fn queue_scene_command(&mut self, command: SceneCommand) -> &mut Self;
}

impl<'w, 's> QueueSceneCommand for Commands<'w, 's> {
    fn queue_scene_command(&mut self, command: SceneCommand) -> &mut Self {
        self.queue(move |world: &mut World| {
            world.write_message(command);
        });
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scene_presentation_defaults_to_fullscreen() {
        assert_eq!(ScenePresentation::default(), ScenePresentation::FULLSCREEN);
        assert!(ScenePresentation::default().covers_previous);
        assert!(ScenePresentation::default().blocks_previous_input);
        assert!(ScenePresentation::default().blocks_previous_update);
    }

    #[test]
    fn open_options_builder_sets_requested_values() {
        let options = OpenSceneOptions::default()
            .with_key("pause")
            .with_presentation(ScenePresentation::PAUSE_OVERLAY)
            .close_current();

        assert_eq!(options.key, Some(SceneKey::new("pause")));
        assert_eq!(options.presentation, ScenePresentation::PAUSE_OVERLAY);
        assert!(options.close_current);
        assert!(!options.clear_stack);
    }

    #[test]
    fn scene_sources_support_jsn_levels_and_runtime_keys() {
        assert_eq!(
            SceneSource::jsn_level("assets/scene.jsn"),
            SceneSource::JsnLevel {
                path: "assets/scene.jsn".to_string()
            }
        );
        assert_eq!(
            SceneSource::runtime("pause_menu"),
            SceneSource::Runtime {
                key: SceneKey::new("pause_menu")
            }
        );
    }

    #[test]
    fn command_helpers_construct_expected_commands() {
        let source = SceneSource::jsn_level("levels/one.jsn");
        assert_eq!(
            SceneCommand::open(source.clone()),
            SceneCommand::Open {
                source: source.clone(),
                options: OpenSceneOptions::default()
            }
        );
        assert_eq!(
            SceneCommand::clear_and_open(source.clone()),
            SceneCommand::ClearAndOpen {
                source,
                options: OpenSceneOptions::default()
            }
        );
    }

    #[test]
    fn scene_stack_starts_empty_with_first_id_available() {
        let stack = SceneStack::default();
        assert!(stack.is_empty());
        assert_eq!(stack.len(), 0);
        assert_eq!(stack.current(), None);
        assert_eq!(stack.next_scene_id(), SceneId(1));
    }
}
