//! Reusable JSON-authored credits roll support for Foundation games.
//!
//! Credits are authored as recursive JSON groups. Runtime systems load that JSON,
//! flatten the group tree into display rows, and generate a scrolling Bevy UI roll
//! beneath an authored [`FoundationCreditsRoll`] marker entity.

use std::{
    fs,
    path::{Path, PathBuf},
};

use bevy::prelude::*;
use serde::{Deserialize, Serialize};

use crate::scene_stack::{SceneCommand, SceneOwner};

const CREDITS_EXIT_PADDING_PIXELS: f32 = 480.0;

/// Installs reusable Foundation credits roll components and systems.
#[derive(Default)]
pub struct FoundationCreditsPlugin;

impl Plugin for FoundationCreditsPlugin {
    fn build(&self, app: &mut App) {
        app.init_resource::<FoundationCreditsRuntimeSettings>()
            .init_resource::<FoundationCreditsAssetRoots>()
            .register_type::<FoundationCreditsRoll>()
            .register_type::<FoundationCreditsRuntime>()
            .register_type::<FoundationCreditsRuntimeSettings>()
            .add_systems(Update, (initialize_credits_rolls, scroll_credits_rolls));
    }
}

/// Directories searched, in order, for relative [`FoundationCreditsRoll`] paths.
///
/// Games should register their own asset directory here so the reusable credits
/// systems stay game-agnostic. The process current directory and its `assets`
/// subdirectory are always tried as final fallbacks.
#[derive(Clone, Debug, Default, Resource)]
pub struct FoundationCreditsAssetRoots {
    /// Ordered directories to search for relative credits paths.
    pub roots: Vec<PathBuf>,
}

/// Runtime policy for reusable Foundation credits systems.
///
/// Standalone games use the default policy: credits systems process any authored
/// credits entity. Editors that keep the authored scene alive during Play should
/// require [`SceneOwner`] so credits UI is generated only for scene-stack runtime
/// copies, not the open editor scene.
#[derive(Clone, Copy, Debug, Default, Reflect, Resource)]
#[reflect(Resource)]
pub struct FoundationCreditsRuntimeSettings {
    /// If true, credits systems ignore entities that are not owned by the scene stack.
    pub require_scene_owner: bool,
}

/// Author-authored marker for a JSON-backed scrolling credits roll.
#[derive(Clone, Debug, Component, Reflect)]
#[reflect(Component)]
pub struct FoundationCreditsRoll {
    /// Asset-relative or project-relative path to the credits JSON file.
    pub credits_path: String,
    /// Asset-relative font path used for generated credits text.
    pub font_path: String,
    /// Vertical scroll speed in pixels per second. Use `0.0` for static centered credits.
    pub scroll_speed_pixels_per_second: f32,
    /// Starting top offset for the generated roll content, in pixels.
    pub start_offset_pixels: f32,
    /// Largest group header font size used for top-level groups.
    pub top_level_header_font_size: f32,
    /// Amount removed from group header font size for each nested level.
    pub header_font_size_step: f32,
    /// Smallest allowed group header font size for deeply nested groups.
    pub minimum_header_font_size: f32,
    /// Font size for person rows.
    pub person_font_size: f32,
    /// Left indentation added for each nested group level, in pixels.
    pub indentation_pixels_per_level: f32,
    /// Vertical space after each generated row, in pixels.
    pub row_gap_pixels: f32,
    /// Default vertical space inserted before each group, in pixels.
    pub group_top_margin_pixels: f32,
    /// Default vertical space inserted after a group header and its direct people, in pixels.
    pub group_bottom_margin_pixels: f32,
}

impl Default for FoundationCreditsRoll {
    fn default() -> Self {
        Self {
            credits_path: "credits.json".to_string(),
            font_path: "fonts/NotoSans-Regular.ttf".to_string(),
            scroll_speed_pixels_per_second: 45.0,
            start_offset_pixels: 220.0,
            top_level_header_font_size: 48.0,
            header_font_size_step: 6.0,
            minimum_header_font_size: 24.0,
            person_font_size: 18.0,
            indentation_pixels_per_level: 32.0,
            row_gap_pixels: 12.0,
            group_top_margin_pixels: 0.0,
            group_bottom_margin_pixels: 20.0,
        }
    }
}

/// Marks UI entities generated by [`FoundationCreditsPlugin`] systems.
///
/// Game-specific authored-UI repair systems can use this marker to avoid treating
/// generated credits rows as BSN-authored scene data.
#[derive(Component, Debug)]
pub struct FoundationGeneratedCreditsUi;

/// Runtime state for an initialized credits roll.
#[derive(Clone, Copy, Debug, Component, Reflect)]
#[reflect(Component)]
pub struct FoundationCreditsRuntime {
    /// Generated UI content entity moved by the scrolling system.
    pub content_entity: Entity,
    /// Current top offset of the generated content, in pixels.
    pub current_top_pixels: f32,
    /// Estimated total content height used to close the scene after scrolling ends.
    pub estimated_content_height_pixels: f32,
}

/// Root JSON document for recursive credits data.
#[derive(Clone, Debug, Default, Deserialize, PartialEq, Serialize)]
pub struct CreditsDocument {
    /// Top-level credits groups.
    #[serde(default)]
    pub groups: Vec<CreditsGroup>,
}

/// A recursive credits group with people and child groups.
#[derive(Clone, Debug, Default, Deserialize, PartialEq, Serialize)]
pub struct CreditsGroup {
    /// Group display name.
    pub name: String,
    /// People credited directly under this group.
    #[serde(default)]
    pub people: Vec<CreditPerson>,
    /// Child groups using the same schema at any nesting depth.
    #[serde(default)]
    pub groups: Vec<CreditsGroup>,
    /// Optional override for this group's top margin, in pixels.
    #[serde(default)]
    pub top_margin_pixels: Option<f32>,
    /// Optional override for this group's bottom margin, in pixels.
    #[serde(default)]
    pub bottom_margin_pixels: Option<f32>,
}

/// A single credited person and role.
#[derive(Clone, Debug, Default, Deserialize, PartialEq, Serialize)]
pub struct CreditPerson {
    /// Person display name.
    pub name: String,
    /// Person role or contribution.
    pub role: String,
}

/// A flattened row ready for credits UI generation.
#[derive(Clone, Debug, PartialEq)]
pub enum CreditsDisplayRow {
    /// Spacer inserted before a group.
    GroupTopMargin { pixels: f32 },
    /// Group heading at the supplied nesting depth.
    Group { name: String, depth: usize },
    /// Person row under the supplied group nesting depth.
    Person {
        name: String,
        role: String,
        depth: usize,
    },
    /// Spacer inserted after a group's direct heading and people rows.
    GroupBottomMargin { pixels: f32 },
}

/// Flattens a recursive credits document into deterministic pre-order rows.
pub fn flatten_credits_document(document: &CreditsDocument) -> Vec<CreditsDisplayRow> {
    flatten_credits_document_with_default_margin(document, 20.0)
}

fn flatten_credits_document_with_default_margin(
    document: &CreditsDocument,
    default_group_bottom_margin_pixels: f32,
) -> Vec<CreditsDisplayRow> {
    let mut display_rows = Vec::new();
    for credits_group in &document.groups {
        flatten_credits_group(
            credits_group,
            0,
            0.0,
            default_group_bottom_margin_pixels,
            &mut display_rows,
        );
    }
    display_rows
}

/// Returns the group header font size for a nesting depth.
pub fn header_font_size_for_depth(credits_roll: &FoundationCreditsRoll, group_depth: usize) -> f32 {
    let depth_reduction = credits_roll.header_font_size_step * group_depth as f32;
    let unclamped_font_size = credits_roll.top_level_header_font_size - depth_reduction;
    unclamped_font_size.max(credits_roll.minimum_header_font_size)
}

fn flatten_credits_group(
    credits_group: &CreditsGroup,
    group_depth: usize,
    default_group_top_margin_pixels: f32,
    default_group_bottom_margin_pixels: f32,
    display_rows: &mut Vec<CreditsDisplayRow>,
) {
    let group_top_margin_pixels = credits_group
        .top_margin_pixels
        .unwrap_or(default_group_top_margin_pixels);
    if group_top_margin_pixels > 0.0 {
        display_rows.push(CreditsDisplayRow::GroupTopMargin {
            pixels: group_top_margin_pixels,
        });
    }

    // Push each group before its contents so the roll reads like a nested outline.
    display_rows.push(CreditsDisplayRow::Group {
        name: credits_group.name.clone(),
        depth: group_depth,
    });

    for credited_person in &credits_group.people {
        display_rows.push(CreditsDisplayRow::Person {
            name: credited_person.name.clone(),
            role: credited_person.role.clone(),
            depth: group_depth,
        });
    }

    let group_bottom_margin_pixels = credits_group
        .bottom_margin_pixels
        .unwrap_or(default_group_bottom_margin_pixels);
    display_rows.push(CreditsDisplayRow::GroupBottomMargin {
        pixels: group_bottom_margin_pixels,
    });

    let child_group_depth = group_depth.saturating_add(1);
    for child_group in &credits_group.groups {
        flatten_credits_group(
            child_group,
            child_group_depth,
            default_group_top_margin_pixels,
            default_group_bottom_margin_pixels,
            display_rows,
        );
    }
}

type CreditsRollInitQuery<'w, 's> = Query<
    'w,
    's,
    (
        Entity,
        &'static FoundationCreditsRoll,
        Option<&'static SceneOwner>,
        Option<&'static ChildOf>,
    ),
    Without<FoundationCreditsRuntime>,
>;

type CreditsRuntimeQuery<'w, 's> = Query<
    'w,
    's,
    (
        &'static FoundationCreditsRoll,
        &'static mut FoundationCreditsRuntime,
    ),
>;

fn initialize_credits_rolls(
    mut commands: Commands,
    settings: Res<FoundationCreditsRuntimeSettings>,
    asset_roots: Res<FoundationCreditsAssetRoots>,
    asset_server: Res<AssetServer>,
    credits_rolls: CreditsRollInitQuery,
    scene_owners: Query<&SceneOwner>,
) {
    for (credits_roll_entity, credits_roll, scene_owner, parent_link) in &credits_rolls {
        let credits_scene_owner = effective_scene_owner(scene_owner, parent_link, &scene_owners);
        if should_skip_credits_runtime_entity(&settings, credits_scene_owner.as_ref()) {
            continue;
        }
        let display_rows = match load_credits_document(&credits_roll.credits_path, &asset_roots) {
            Ok(credits_document) => flatten_credits_document_with_default_margin(
                &credits_document,
                credits_roll.group_bottom_margin_pixels,
            ),
            Err(load_error) => {
                warn!(
                    "Failed to load FoundationCreditsRoll JSON `{}`: {load_error}",
                    credits_roll.credits_path
                );
                fallback_credits_error_rows(&load_error)
            }
        };
        let estimated_content_height_pixels =
            estimate_credits_content_height(credits_roll, &display_rows);
        let content_entity = spawn_credits_content(
            &mut commands,
            &asset_server,
            credits_roll,
            &display_rows,
            credits_scene_owner,
        );
        commands
            .entity(credits_roll_entity)
            .replace_children(&[content_entity]);
        commands
            .entity(credits_roll_entity)
            .insert(FoundationCreditsRuntime {
                content_entity,
                current_top_pixels: credits_roll.start_offset_pixels,
                estimated_content_height_pixels,
            });
    }
}

fn scroll_credits_rolls(
    time: Res<Time>,
    mut credits_rolls: CreditsRuntimeQuery,
    mut content_nodes: Query<&mut Node>,
    mut scene_commands: MessageWriter<SceneCommand>,
) {
    let delta_seconds = time.delta_secs();
    for (credits_roll, mut credits_runtime) in &mut credits_rolls {
        if credits_roll.scroll_speed_pixels_per_second == 0.0 {
            // Static credits keep their initial percent-based centered position.
            continue;
        }

        credits_runtime.current_top_pixels -=
            credits_roll.scroll_speed_pixels_per_second * delta_seconds;
        if let Ok(mut content_node) = content_nodes.get_mut(credits_runtime.content_entity) {
            content_node.top = Val::Px(credits_runtime.current_top_pixels);
        }

        let content_bottom_pixels =
            credits_runtime.current_top_pixels + credits_runtime.estimated_content_height_pixels;
        if content_bottom_pixels < -CREDITS_EXIT_PADDING_PIXELS {
            // Keep a safety margin because Bevy text layout can be taller than raw font sizes.
            scene_commands.write(SceneCommand::CloseCurrent);
        }
    }
}

fn estimate_credits_content_height(
    credits_roll: &FoundationCreditsRoll,
    display_rows: &[CreditsDisplayRow],
) -> f32 {
    let rows_height = display_rows
        .iter()
        .map(|display_row| match display_row {
            CreditsDisplayRow::Group { depth, .. } => {
                header_font_size_for_depth(credits_roll, *depth)
            }
            CreditsDisplayRow::Person { .. } => credits_roll.person_font_size,
            CreditsDisplayRow::GroupTopMargin { pixels } => *pixels,
            CreditsDisplayRow::GroupBottomMargin { pixels } => *pixels,
        })
        .sum::<f32>();
    let row_gap_count = display_rows.len().saturating_sub(1) as f32;
    rows_height + credits_roll.row_gap_pixels * row_gap_count
}

fn spawn_credits_content(
    commands: &mut Commands,
    asset_server: &AssetServer,
    credits_roll: &FoundationCreditsRoll,
    display_rows: &[CreditsDisplayRow],
    scene_owner: Option<SceneOwner>,
) -> Entity {
    let content_width = Val::Percent(100.0);
    let content_top = if credits_roll.scroll_speed_pixels_per_second == 0.0 {
        // Static credits start at screen center to match the working authored text baseline.
        Val::Percent(50.0)
    } else {
        Val::Px(credits_roll.start_offset_pixels)
    };
    let content_entity = commands
        .spawn((
            Node {
                position_type: PositionType::Absolute,
                top: content_top,
                width: content_width,
                flex_direction: FlexDirection::Column,
                align_items: AlignItems::Center,
                row_gap: Val::Px(credits_roll.row_gap_pixels),
                ..default()
            },
            FoundationGeneratedCreditsUi,
            Name::new("Foundation Credits Content"),
        ))
        .id();
    insert_scene_owner(commands, content_entity, scene_owner);

    let row_entities = display_rows
        .iter()
        .map(|display_row| {
            spawn_credits_row(
                commands,
                asset_server,
                credits_roll,
                display_row,
                scene_owner,
            )
        })
        .collect::<Vec<_>>();
    commands
        .entity(content_entity)
        .replace_children(&row_entities);

    content_entity
}

fn spawn_credits_row(
    commands: &mut Commands,
    asset_server: &AssetServer,
    credits_roll: &FoundationCreditsRoll,
    display_row: &CreditsDisplayRow,
    scene_owner: Option<SceneOwner>,
) -> Entity {
    let (row_text, row_font_size) = match display_row {
        CreditsDisplayRow::GroupTopMargin { pixels } => {
            return spawn_group_margin(commands, *pixels, scene_owner);
        }
        CreditsDisplayRow::Group { name, depth } => {
            let header_font_size = header_font_size_for_depth(credits_roll, *depth);
            (name.to_uppercase(), header_font_size)
        }
        CreditsDisplayRow::Person { name, role, .. } => {
            return spawn_credit_person_row(
                commands,
                asset_server,
                credits_roll,
                name,
                role,
                scene_owner,
            );
        }
        CreditsDisplayRow::GroupBottomMargin { pixels } => {
            return spawn_group_margin(commands, *pixels, scene_owner);
        }
    };

    let row_entity = commands
        .spawn((
            Node {
                align_self: AlignSelf::Center,
                ..default()
            },
            Text::new(row_text.clone()),
            credits_text_font(asset_server, credits_roll, row_font_size),
            TextColor(Color::WHITE),
            FoundationGeneratedCreditsUi,
            Name::new(row_text),
        ))
        .id();
    insert_scene_owner(commands, row_entity, scene_owner);
    row_entity
}

fn spawn_credit_person_row(
    commands: &mut Commands,
    asset_server: &AssetServer,
    credits_roll: &FoundationCreditsRoll,
    credited_person_name: &str,
    credited_person_role: &str,
    scene_owner: Option<SceneOwner>,
) -> Entity {
    if credited_person_role.trim().is_empty() {
        return spawn_centered_credit_text(
            commands,
            asset_server,
            credits_roll,
            credited_person_name,
            credits_roll.person_font_size,
            scene_owner,
        );
    }

    let name_column_width = Val::Px(300.0);
    let role_column_width = Val::Px(300.0);
    let center_gap_width = Val::Px(28.0);
    let row_width = Val::Px(628.0);
    let row_entity = commands
        .spawn((
            Node {
                align_items: AlignItems::Center,
                align_self: AlignSelf::Center,
                column_gap: center_gap_width,
                flex_direction: FlexDirection::Row,
                justify_content: JustifyContent::Center,
                width: row_width,
                ..default()
            },
            FoundationGeneratedCreditsUi,
            Name::new(format!("{credited_person_name} Credit Row")),
        ))
        .id();
    insert_scene_owner(commands, row_entity, scene_owner);

    let name_text = CreditPersonTextSpec {
        value: credited_person_name,
        font_size: credits_roll.person_font_size,
        column_width: name_column_width,
        horizontal_alignment: JustifyContent::FlexEnd,
    };
    let name_text_cell_entity =
        spawn_credit_person_text_cell(commands, asset_server, credits_roll, name_text, scene_owner);
    let role_text = CreditPersonTextSpec {
        value: credited_person_role,
        font_size: credits_roll.person_font_size,
        column_width: role_column_width,
        horizontal_alignment: JustifyContent::FlexStart,
    };
    let role_text_cell_entity =
        spawn_credit_person_text_cell(commands, asset_server, credits_roll, role_text, scene_owner);
    commands
        .entity(row_entity)
        .replace_children(&[name_text_cell_entity, role_text_cell_entity]);

    row_entity
}

fn spawn_centered_credit_text(
    commands: &mut Commands,
    asset_server: &AssetServer,
    credits_roll: &FoundationCreditsRoll,
    text_value: &str,
    font_size: f32,
    scene_owner: Option<SceneOwner>,
) -> Entity {
    let text_entity = commands
        .spawn((
            Node {
                align_self: AlignSelf::Center,
                ..default()
            },
            Text::new(text_value.to_string()),
            credits_text_font(asset_server, credits_roll, font_size),
            TextColor(Color::WHITE),
            // Credits rows must stay one row tall while scrolling through the clipped viewport.
            TextLayout::no_wrap(),
            FoundationGeneratedCreditsUi,
            Name::new(text_value.to_string()),
        ))
        .id();
    insert_scene_owner(commands, text_entity, scene_owner);
    text_entity
}

struct CreditPersonTextSpec<'a> {
    value: &'a str,
    font_size: f32,
    column_width: Val,
    horizontal_alignment: JustifyContent,
}

fn spawn_credit_person_text_cell(
    commands: &mut Commands,
    asset_server: &AssetServer,
    credits_roll: &FoundationCreditsRoll,
    text_spec: CreditPersonTextSpec,
    scene_owner: Option<SceneOwner>,
) -> Entity {
    let cell_entity = commands
        .spawn((
            Node {
                width: text_spec.column_width,
                justify_content: text_spec.horizontal_alignment,
                ..default()
            },
            FoundationGeneratedCreditsUi,
            Name::new(format!("{} Credit Cell", text_spec.value)),
        ))
        .id();
    insert_scene_owner(commands, cell_entity, scene_owner);

    let text_entity = commands
        .spawn((
            Text::new(text_spec.value.to_string()),
            credits_text_font(asset_server, credits_roll, text_spec.font_size),
            TextColor(Color::WHITE),
            // The column cell controls horizontal alignment, while text layout prevents wrapping.
            TextLayout::no_wrap(),
            FoundationGeneratedCreditsUi,
            Name::new(text_spec.value.to_string()),
        ))
        .id();
    insert_scene_owner(commands, text_entity, scene_owner);

    commands
        .entity(cell_entity)
        .replace_children(&[text_entity]);

    cell_entity
}

fn credits_text_font(
    asset_server: &AssetServer,
    credits_roll: &FoundationCreditsRoll,
    font_size: f32,
) -> TextFont {
    let font_path = credits_roll.font_path.trim();
    if font_path.is_empty() {
        return TextFont::from_font_size(font_size);
    }

    TextFont {
        font: FontSource::Handle(asset_server.load(font_path.to_string())),
        font_size: FontSize::Px(font_size),
        ..default()
    }
}

fn spawn_group_margin(
    commands: &mut Commands,
    group_margin_pixels: f32,
    scene_owner: Option<SceneOwner>,
) -> Entity {
    let spacer_height = Val::Px(group_margin_pixels);
    let spacer_entity = commands
        .spawn((
            Node {
                align_self: AlignSelf::Center,
                height: spacer_height,
                ..default()
            },
            FoundationGeneratedCreditsUi,
            Name::new("Foundation Credits Group Margin"),
        ))
        .id();
    insert_scene_owner(commands, spacer_entity, scene_owner);
    spacer_entity
}

fn load_credits_document(
    credits_path: &str,
    asset_roots: &FoundationCreditsAssetRoots,
) -> Result<CreditsDocument, String> {
    // The current directory and its `assets` subdirectory are generic fallbacks;
    // game-specific directories must come from the configured asset roots.
    let mut search_roots = asset_roots.roots.clone();
    if let Ok(current_directory) = std::env::current_dir() {
        search_roots.push(current_directory.join("assets"));
        search_roots.push(current_directory);
    }

    let credits_file_path = resolve_credits_file_path(credits_path, &search_roots)
        .ok_or_else(|| format!("could not resolve credits path `{credits_path}`"))?;
    let credits_json = fs::read_to_string(&credits_file_path)
        .map_err(|read_error| format!("{} ({read_error})", credits_file_path.display()))?;
    serde_json::from_str::<CreditsDocument>(&credits_json)
        .map_err(|parse_error| format!("{} ({parse_error})", credits_file_path.display()))
}

fn resolve_credits_file_path(credits_path: &str, search_roots: &[PathBuf]) -> Option<PathBuf> {
    let requested_credits_path = Path::new(credits_path.trim());
    if requested_credits_path.is_absolute() && requested_credits_path.is_file() {
        return Some(requested_credits_path.to_path_buf());
    }

    search_roots
        .iter()
        .map(|search_root| search_root.join(requested_credits_path))
        .find(|candidate_path| candidate_path.is_file())
}

fn insert_scene_owner(
    commands: &mut Commands,
    owned_entity: Entity,
    scene_owner: Option<SceneOwner>,
) {
    if let Some(scene_owner) = scene_owner {
        commands.entity(owned_entity).insert(scene_owner);
    }
}

fn effective_scene_owner(
    scene_owner: Option<&SceneOwner>,
    parent_link: Option<&ChildOf>,
    scene_owners: &Query<&SceneOwner>,
) -> Option<SceneOwner> {
    // Authored scene components may inherit ownership from their loaded UI root.
    scene_owner.copied().or_else(|| {
        parent_link.and_then(|parent_link| scene_owners.get(parent_link.0).ok().copied())
    })
}

fn fallback_credits_error_rows(load_error: &str) -> Vec<CreditsDisplayRow> {
    vec![
        CreditsDisplayRow::Group {
            name: "Credits unavailable".to_string(),
            depth: 0,
        },
        CreditsDisplayRow::Person {
            name: "Failed to load credits".to_string(),
            role: load_error.to_string(),
            depth: 0,
        },
    ]
}

fn should_skip_credits_runtime_entity(
    settings: &FoundationCreditsRuntimeSettings,
    scene_owner: Option<&SceneOwner>,
) -> bool {
    settings.require_scene_owner && scene_owner.is_none()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn credits_document_flattens_recursive_groups_in_pre_order() {
        let credits_document = serde_json::from_str::<CreditsDocument>(
            r#"
            {
                "groups": [
                    {
                        "name": "Studio A",
                        "people": [],
                        "groups": [
                            {
                                "name": "Team 1",
                                "people": [
                                    { "name": "Alice", "role": "Developer" },
                                    { "name": "Bob", "role": "Designer" }
                                ],
                                "groups": []
                            },
                            {
                                "name": "Team 2",
                                "people": [
                                    { "name": "Charlie", "role": "Tester" }
                                ],
                                "groups": []
                            }
                        ]
                    }
                ]
            }
            "#,
        )
        .expect("Credits JSON should match the documented recursive schema");

        assert_eq!(
            flatten_credits_document(&credits_document),
            vec![
                CreditsDisplayRow::Group {
                    name: "Studio A".to_string(),
                    depth: 0,
                },
                CreditsDisplayRow::GroupBottomMargin { pixels: 20.0 },
                CreditsDisplayRow::Group {
                    name: "Team 1".to_string(),
                    depth: 1,
                },
                CreditsDisplayRow::Person {
                    name: "Alice".to_string(),
                    role: "Developer".to_string(),
                    depth: 1,
                },
                CreditsDisplayRow::Person {
                    name: "Bob".to_string(),
                    role: "Designer".to_string(),
                    depth: 1,
                },
                CreditsDisplayRow::GroupBottomMargin { pixels: 20.0 },
                CreditsDisplayRow::Group {
                    name: "Team 2".to_string(),
                    depth: 1,
                },
                CreditsDisplayRow::Person {
                    name: "Charlie".to_string(),
                    role: "Tester".to_string(),
                    depth: 1,
                },
                CreditsDisplayRow::GroupBottomMargin { pixels: 20.0 },
            ]
        );
    }

    #[test]
    fn credits_document_supports_deeply_nested_groups() {
        let deepest_group = CreditsGroup {
            name: "Depth 3".to_string(),
            people: vec![CreditPerson {
                name: "Deep Person".to_string(),
                role: "Deep Role".to_string(),
            }],
            groups: Vec::new(),
            top_margin_pixels: None,
            bottom_margin_pixels: None,
        };
        let credits_document = CreditsDocument {
            groups: vec![CreditsGroup {
                name: "Depth 0".to_string(),
                people: Vec::new(),
                groups: vec![CreditsGroup {
                    name: "Depth 1".to_string(),
                    people: Vec::new(),
                    groups: vec![CreditsGroup {
                        name: "Depth 2".to_string(),
                        people: Vec::new(),
                        groups: vec![deepest_group],
                        top_margin_pixels: None,
                        bottom_margin_pixels: None,
                    }],
                    top_margin_pixels: None,
                    bottom_margin_pixels: None,
                }],
                top_margin_pixels: None,
                bottom_margin_pixels: None,
            }],
        };

        let display_rows = flatten_credits_document(&credits_document);

        assert!(display_rows.contains(&CreditsDisplayRow::Person {
            name: "Deep Person".to_string(),
            role: "Deep Role".to_string(),
            depth: 3,
        }));
        assert_eq!(
            display_rows.last(),
            Some(&CreditsDisplayRow::GroupBottomMargin { pixels: 20.0 })
        );
    }

    #[test]
    fn credits_group_bottom_margin_can_be_overridden_per_group() {
        let credits_document = CreditsDocument {
            groups: vec![CreditsGroup {
                name: "Custom Spacing".to_string(),
                people: Vec::new(),
                groups: Vec::new(),
                top_margin_pixels: None,
                bottom_margin_pixels: Some(64.0),
            }],
        };

        assert_eq!(
            flatten_credits_document(&credits_document),
            vec![
                CreditsDisplayRow::Group {
                    name: "Custom Spacing".to_string(),
                    depth: 0,
                },
                CreditsDisplayRow::GroupBottomMargin { pixels: 64.0 },
            ]
        );
    }

    #[test]
    fn credits_group_top_margin_can_be_overridden_per_group() {
        let credits_document = CreditsDocument {
            groups: vec![CreditsGroup {
                name: "Top Spacing".to_string(),
                people: Vec::new(),
                groups: Vec::new(),
                top_margin_pixels: Some(48.0),
                bottom_margin_pixels: None,
            }],
        };

        assert_eq!(
            flatten_credits_document(&credits_document),
            vec![
                CreditsDisplayRow::GroupTopMargin { pixels: 48.0 },
                CreditsDisplayRow::Group {
                    name: "Top Spacing".to_string(),
                    depth: 0,
                },
                CreditsDisplayRow::GroupBottomMargin { pixels: 20.0 },
            ]
        );
    }

    #[test]
    fn group_header_font_size_shrinks_by_depth_and_clamps() {
        let credits_roll = FoundationCreditsRoll {
            top_level_header_font_size: 48.0,
            header_font_size_step: 8.0,
            minimum_header_font_size: 28.0,
            ..default()
        };

        assert_eq!(header_font_size_for_depth(&credits_roll, 0), 48.0);
        assert_eq!(header_font_size_for_depth(&credits_roll, 1), 40.0);
        assert_eq!(header_font_size_for_depth(&credits_roll, 2), 32.0);
        assert_eq!(header_font_size_for_depth(&credits_roll, 99), 28.0);
    }

    #[test]
    fn relative_credits_paths_resolve_through_configured_asset_roots() {
        let asset_root = std::env::temp_dir().join(format!(
            "foundation-credits-roots-test-{}",
            std::process::id()
        ));
        fs::create_dir_all(&asset_root).expect("test asset root should be created");
        let credits_file_path = asset_root.join("credits.json");
        fs::write(&credits_file_path, "{}").expect("test credits file should be written");

        let resolved_path =
            resolve_credits_file_path("credits.json", std::slice::from_ref(&asset_root));

        assert_eq!(resolved_path, Some(credits_file_path));
        let _ = fs::remove_dir_all(asset_root);
    }

    #[test]
    fn unresolvable_credits_paths_return_none() {
        let resolved_path =
            resolve_credits_file_path("foundation-definitely-missing-credits.json", &[]);

        assert_eq!(resolved_path, None);
    }

    #[test]
    fn credits_roll_defaults_to_readable_scrolling_values() {
        let credits_roll = FoundationCreditsRoll::default();

        assert_eq!(credits_roll.credits_path, "credits.json");
        assert_eq!(credits_roll.font_path, "fonts/NotoSans-Regular.ttf");
        assert!(credits_roll.scroll_speed_pixels_per_second > 0.0);
        assert!(credits_roll.top_level_header_font_size > credits_roll.minimum_header_font_size);
        assert!(credits_roll.person_font_size < credits_roll.minimum_header_font_size);
        assert_eq!(credits_roll.group_top_margin_pixels, 0.0);
        assert_eq!(credits_roll.group_bottom_margin_pixels, 20.0);
    }
}
